### PR TITLE
tmp

### PR DESCRIPTION
**Pull request by 12tbuchman**
This change is [Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/4)

### CODE REVIEW

**Review by tracyofleming — APPROVED** [review]
I reviewed this change and converted the Inked notation in the file actual objects in Excel. I also replicated the notation for the Tether Joystick.

**Review by 12tbuchman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/4)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/4#-N7kiaSy0a8WpYbyTCdS):*
please create your own PR for these changes

**Comment by 12tbuchman** [comment]
this pull request was only for testing. it was not meant to be merged.

**Comment by tracyofleming** [comment]
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/4#-N7kiaSy0a8WpYbyTCdS):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

please create your own PR for these changes
</blockquote></details>

Noted Tyler

**Pull request closed without merging**
